runtime: plugin
action:
  title: Update
  description: "Command to fetch and install the latest version of plasmactl"
  options:
    - name: username
      title: Username
      type: string
      default: ""
    - name: password
      title: Password
      type: string
      default: ""
    - name: config
      title: Config file
      description: Use specified config with metadata for update
      default: ""
